# Generated by Django 4.1.4 on 2023-01-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vski', '0003_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='media/blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
